select P.IMIE, P.NAZWISKO, P.NR_EW, P.NR_KARTY,
       K.DZIEN_MIES, TO_CHAR(K.CZAS_OD, 'HH24:MI') CZAS_OD, TO_CHAR(K.CZAS_DO, 'HH24:MI') CZAS_DO,
       D.WORKDAY_DATE, TO_CHAR(D.DATE_TIME_FROM, 'HH24:MI') DYZUR_OD, TO_CHAR(D.DATE_TIME_TO, 'HH24:MI') DYZUR_DO
from T_PRAC P, NT_KP_KDR_KALENDARZE_PRAC K, KP_RCP_WORK_TIME_EVENTS D
where K.DZIEN_MIES BETWEEN '26/03/01' AND '26/05/31'
AND P.PRAC_ID = K.PRAC_ID
AND D.PRAC_ID = P.PRAC_ID
AND D.WTET_ID = 18
AND TRUNC(K.DZIEN_MIES) = TRUNC(D.WORKDAY_DATE)
AND K.TYP_DNIA IS NULL
AND D.DATE_TIME_FROM < TRUNC(K.DZIEN_MIES) + (K.CZAS_DO - TRUNC(K.CZAS_DO))
                     + CASE WHEN (K.CZAS_DO - TRUNC(K.CZAS_DO)) < (K.CZAS_OD - TRUNC(K.CZAS_OD))
                            THEN 1 ELSE 0 END
AND D.DATE_TIME_TO   > TRUNC(K.DZIEN_MIES) + (K.CZAS_OD - TRUNC(K.CZAS_OD))
ORDER BY P.NAZWISKO, P.IMIE, K.DZIEN_MIES
