WITH cal AS (
    select P.PRAC_ID, P.IMIE, P.NAZWISKO, P.NR_EW, P.NR_KARTY,
           K.DZIEN_MIES, K.CZAS_OD, K.CZAS_DO,
           TRUNC(K.DZIEN_MIES) + (K.CZAS_OD - TRUNC(K.CZAS_OD)) AS CAL_START,
           TRUNC(K.DZIEN_MIES) + (K.CZAS_DO - TRUNC(K.CZAS_DO))
           + CASE WHEN (K.CZAS_DO - TRUNC(K.CZAS_DO)) < (K.CZAS_OD - TRUNC(K.CZAS_OD))
                  THEN 1 ELSE 0 END AS CAL_END
    from T_PRAC P, NT_KP_KDR_KALENDARZE_PRAC K
    where K.DZIEN_MIES BETWEEN '26/03/01' AND '26/05/31'
    AND P.PRAC_ID = K.PRAC_ID
    AND K.TYP_DNIA IS NULL
)
select C.IMIE, C.NAZWISKO, C.NR_EW, C.NR_KARTY,
       C.DZIEN_MIES,
       TO_CHAR(C.CZAS_OD,       'HH24:MI') CZAS_OD,
       TO_CHAR(C.CZAS_DO,       'HH24:MI') CZAS_DO,
       D.WORKDAY_DATE,
       TO_CHAR(D.DATE_TIME_FROM, 'HH24:MI') DYZUR_OD,
       TO_CHAR(D.DATE_TIME_TO,   'HH24:MI') DYZUR_DO
from cal C, KP_RCP_WORK_TIME_EVENTS D
where D.PRAC_ID = C.PRAC_ID
AND D.WTET_ID = 18
AND TRUNC(C.DZIEN_MIES) = TRUNC(D.WORKDAY_DATE)
AND D.DATE_TIME_FROM < C.CAL_END
AND D.DATE_TIME_TO   > C.CAL_START
ORDER BY C.NAZWISKO, C.IMIE, C.DZIEN_MIES
