SELECT 'KP_REQ_REQUEST' AS zrodlo, ID, GUID, SYMBOL FROM KP_REQ_REQUEST              WHERE SYMBOL = '00010/2026'
UNION ALL
SELECT 'KP_REQ_DECLARATION_REQUESTS', ID, GUID, SYMBOL FROM KP_REQ_DECLARATION_REQUESTS WHERE SYMBOL = '00010/2026';

DELETE FROM KP_REQ_COST_REQUESTS
 WHERE KRRQ_ID IN (SELECT ID FROM KP_REQ_REQUEST WHERE SYMBOL = '00010/2026');

DELETE FROM KP_REQ_EMPLOYEE
 WHERE KRRQ_ID IN (SELECT ID FROM KP_REQ_REQUEST WHERE SYMBOL = '00010/2026');

DELETE FROM PA_WFL_DOC_ASSOCIATIONS
 WHERE DOCUMENT_GUID IN (SELECT GUID FROM KP_REQ_REQUEST WHERE SYMBOL = '00010/2026');

 DELETE FROM KP_REQ_REQUEST
 WHERE SYMBOL = '00010/2026';

DELETE FROM KP_KDR_EMPL_DECL_PERIODS
 WHERE DERE_ID IN (SELECT ID FROM KP_REQ_DECLARATION_REQUESTS WHERE SYMBOL = '00010/2026');

DELETE FROM KP_REQ_DECLARATION_REQUESTS
 WHERE SYMBOL = '00010/2026';
